import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/my-components/Navbar";

const inter = Inter({ subsets: ["latin"] , variable : "--font-sans"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layoutt({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section lang="en">
        <div className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
        >
          <Navbar />
          {children}
        </div>
        
    </section>
  );
}
