import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/my-components/Navbar";

const inter = Inter({subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section lang="en" className={inter.className}>
        <div className={cn(
          "min-h-screen bg-background font-sans antialiased"
        )}
        >
          <Navbar />
          {children}
        </div>
        
    </section>
  );
}
